export const UPDATE_LAUNCH_DATA = "UPDATE_LAUNCH_DATA";
export const UPDATE_LAUNCH_DATA_LOADER = "UPDATE_LAUNCH_DATA_LOADER";
export const UPDATE_SELECTED_LAUNCH_DETAIL = "UPDATE_SELECTED_LAUNCH_DETAIL";
export const UPDATE_FULL_LAUNCH_DETAILS_OF_SELECTED_LAUNCH =
  "UPDATE_FULL_LAUNCH_DETAILS_OF_SELECTED_LAUNCH";
export const UPDATE_FULL_LAUNCH_DETAILS_LOADING =
  "UPDATE_FULL_LAUNCH_DETAILS_LOADING";

//----------------------------------------------------------------------------//
export const UPDATE_ROCKET_DATA = "UPDATE_ROCKET_DATA";
export const UPDATE_ROCKET_DATA_LOADER = "UPDATE_ROCKET_DATA_LOADER";
//----------------------------------------------------------------------------//
export const UPDATE_MISSION_DATA = "UPDATE_MISSION_DATA";
export const UPDATE_MISSION_DATA_LOADER = "UPDATE_MISSION_DATA_LOADER";
